name: Auto Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: black
        uses: psf/black@stable
        with:
          options: '.'
      - name: Check for midified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: 'Push Changes'
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Rodrigo Souza'
          git config --global user.email 'souzabpr@tuta.io'
          git remote set-url origin https://x-access-token:${{secrets.TOKEN}}@github.com/${{github.repository}}
          git commit -am "style: auto lint with black"
          git push
